### ISSUE TITLE
Segmentation Fault in Hector Slam

### ISSUE THREAD

**Issue by nwotero** [tu-darmstadt-ros-pkg/hector_slam#23]
When I rotate my base 90 degrees, Hector Slam consistently seg faults. According to GDB, this segmentation fault occurs in GridMapCacheArray::containsCachedData(int, float&). From the source, it seems that Line 82 is the culprit:  const CachedMapElement& elem (cacheArray[index]);

This is a really easy patch, but I am unsure if it points to a more serious underlying problem.

If this is because of a race condition, a simple if statement would only be covering up the problem.

**Comment by nwotero** [comment]
Full Backtrace:

#0  0x00000000005df7db in GridMapCacheArray::containsCachedData(int, float&) ()
#1  0x0000000000608b5e in hectorslam::OccGridMapUtil<hectorslam::OccGridMapBase<LogOddsCell, GridMapLogOddsFunctions>, GridMapCacheArray>::interpMapValueWithDerivatives(Eigen::Matrix<float, 2, 1, 0, 2, 1> const&) ()
#2  0x00000000005fe779 in hectorslam::OccGridMapUtil<hectorslam::OccGridMapBase<LogOddsCell, GridMapLogOddsFunctions>, GridMapCacheArray>::getCompleteHessianDerivs(Eigen::Matrix<float, 3, 1, 0, 3, 1> const&, hectorslam::DataPointContainer<Eigen::Matrix<float, 2, 1, 0, 2, 1> > const&, Eigen::Matrix<float, 3, 3, 0, 3, 3>&, Eigen::Matrix<float, 3, 1, 0, 3, 1>&) ()
#3  0x00000000005f3475 in hectorslam::ScanMatcher<hectorslam::OccGridMapUtilConfig<hectorslam::OccGridMapBase<LogOddsCell, GridMapLogOddsFunctions> > >::estimateTransformationLogLh(Eigen::Matrix<float, 3, 1, 0, 3, 1>&, hectorslam::OccGridMapUtilConfig<hectorslam::OccGridMapBase<LogOddsCell, GridMapLogOddsFunctions> >&, hectorslam::DataPointContainer<Eigen::Matrix<float, 2, 1, 0, 2, 1> > const&)
    ()
#4  0x00000000005e5237 in hectorslam::ScanMatcher<hectorslam::OccGridMapUtilConfig<hectorslam::OccGridMapBase<LogOddsCell, GridMapLogOddsFunctions> > >::matchData(Eigen::Matrix<float, 3, 1, 0, 3, 1> const&, hectorslam::OccGridMapUtilConfig<hectorslam::OccGridMapBase<LogOddsCell, GridMapLogOddsFunctions> >&, hectorslam::DataPointContainer<Eigen::Matrix<float, 2, 1, 0, 2, 1> > const&, Eigen::Matrix<float, 3, 3, 0, 3, 3>&, int) ()
#5  0x00000000005dfcb4 in hectorslam::MapProcContainer::matchData(Eigen::Matrix<float, 3, 1, 0, 3, 1> const&, hectorslam::DataPointContainer<Eigen::Matrix<float---Type <return> to continue, or q <return> to quit---
, 2, 1, 0, 2, 1> > const&, Eigen::Matrix<float, 3, 3, 0, 3, 3>&, int) ()
#6  0x00000000005e05b5 in hectorslam::MapRepMultiMap::matchData(Eigen::Matrix<float, 3, 1, 0, 3, 1> const&, hectorslam::DataPointContainer<Eigen::Matrix<float, 2, 1, 0, 2, 1> > const&, Eigen::Matrix<float, 3, 3, 0, 3, 3>&) ()
#7  0x00000000005e0942 in hectorslam::HectorSlamProcessor::update(hectorslam::DataPointContainer<Eigen::Matrix<float, 2, 1, 0, 2, 1> > const&, Eigen::Matrix<float, 3, 1, 0, 3, 1> const&, bool) ()
#8  0x00000000005d6ba2 in HectorMappingRos::scanCallback(sensor_msgs::LaserScan_std::allocator<void > const&) ()
#9  0x000000000063622a in boost::_mfi::mf1<void, HectorMappingRos, sensor_msgs::LaserScan_std::allocator<void > const&>::operator()(HectorMappingRos_, sensor_msgs::LaserScan_std::allocator<void > const&) const ()
#10 0x000000000062d0b1 in void boost::_bi::list2<boost::_bi::value<HectorMappingRos_>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, HectorMappingRos, sensor_msgs::LaserScan_<std::allocator<void> > const&>, boost::_bi::list1<sensor_msgs::LaserScan_std::allocator<void > const&> >(boost::_bi::type<void>, boost::_mfi::mf1<void, HectorMappingRos, sensor_msgs::LaserScan_std::allocator<void > const&>&, boost::_bi::list1<sensor_msgs::LaserScan_std::allocator<void > const&>&, int) ()
#11 0x0000000000624f70 in void boost::_bi::bind_t<void, boost::_mfi::mf1<void, HectorMappingRos, sensor_msgs::LaserScan_std::allocator<void > const&>, boost::_bi::list2boost::_bi::value<HectorMappingRos*, boost::arg<1> > >::operator()<sensor_msgs::LaserScan_std::allocator<void > >(sensor_msgs::LaserScan_<std::all---Type <return> to continue, or q <return> to quit---
ocator<void> > const&) ()
#12 0x000000000061ac81 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, HectorMappingRos, sensor_msgs::LaserScan_<std::allocator<void> > const&>, boost::_bi::list2boost::_bi::value<HectorMappingRos*, boost::arg<1> > >, void, sensor_msgs::LaserScan_std::allocator<void > const&>::invoke(boost::detail::function::function_buffer&, sensor_msgs::LaserScan_std::allocator<void > const&) ()
#13 0x000000000066c8b7 in boost::function1<void, sensor_msgs::LaserScan_<std::allocator<void> > const&>::operator()(sensor_msgs::LaserScan_std::allocator<void > const&) const ()
#14 0x0000000000669943 in ros::SubscriptionCallbackHelperT<sensor_msgs::LaserScan_<std::allocator<void> > const&, void>::call(ros::SubscriptionCallbackHelperCallParams&) ()
#15 0x00007ffff75449c5 in ros::SubscriptionQueue::call() ()
   from /opt/ros/indigo/lib/libroscpp.so
#16 0x00007ffff7502777 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS_) () from /opt/ros/indigo/lib/libroscpp.so
#17 0x00007ffff7503583 in ros::CallbackQueue::callAvailable(ros::WallDuration)
    () from /opt/ros/indigo/lib/libroscpp.so
#18 0x00007ffff75474e5 in ros::SingleThreadedSpinner::spin(ros::CallbackQueue_)
    () from /opt/ros/indigo/lib/libroscpp.so
#19 0x00007ffff752faeb in ros::spin() () from /opt/ros/indigo/lib/libroscpp.so
#20 0x000000000067023f in main ()
